In [34]:
import pandas as pd
import numpy as np

In [38]:
df = pd.read_csv('Exercise_1.csv')
df

Customer ID      Entity        Name   Surname  Age at time of purchase  \
0         C0028  Individual     Madalyn    Mercer                     19.0   
1         C0027  Individual        Lara  Carrillo                     22.0   
2         C0112  Individual     Donavan   Flowers                     22.0   
3         C0160  Individual      Darien    Dorsey                     22.0   
4         C0014  Individual  Alessandra     Perry                     25.0   
..          ...         ...         ...       ...                      ...   
190       C0174        Firm     Marleez        Co                      NaN   
191       C0174        Firm     Marleez        Co                      NaN   
192       C0174        Firm     Marleez        Co                      NaN   
193       C0174        Firm     Marleez        Co                      NaN   
194       C0174        Firm     Marleez        Co                      NaN   

          Y Gender Country       State     Purpose  ...  Unnamed: 15  \
0    1986.0      F     USA  California        Home  ...          NaN   
1    1983.0      F     USA  California        Home  ...          NaN   
2    1985.0      M     USA  California        Home  ...          NaN   
3    1985.0      M     USA  California  Investment  ...          NaN   
4    1979.0      F     USA  California        Home  ...          NaN   
..      ...    ...     ...         ...         ...  ...          ...   
190     NaN    NaN     USA  California  Investment  ...          NaN   
191     NaN    NaN     USA  California  Investment  ...          NaN   
192     NaN    NaN     USA  California  Investment  ...          NaN   
193     NaN    NaN     USA  California  Investment  ...          NaN   
194     NaN    NaN     USA  California  Investment  ...          NaN   

    Unnamed: 16 Unnamed: 17  Unnamed: 18  Unnamed: 19  Unnamed: 20  \
0           NaN         NaN          NaN          NaN          NaN   
1           NaN         NaN          NaN          NaN          NaN   
2           NaN         NaN          NaN          NaN          NaN   
3           NaN         NaN          NaN          NaN          NaN   
4           NaN         NaN          NaN          NaN          NaN   
..          ...         ...          ...          ...          ...   
190         NaN         NaN          NaN          NaN          NaN   
191         NaN         NaN          NaN          NaN          NaN   
192         NaN         NaN          NaN          NaN          NaN   
193         NaN         NaN          NaN          NaN          NaN   
194         NaN         NaN          NaN          NaN          NaN   

    Unnamed: 21 Unnamed: 22 Unnamed: 23 Unnamed: 24  
0           NaN         NaN         NaN         NaN  
1           NaN         NaN         NaN         NaN  
2           NaN         NaN         NaN         NaN  
3           NaN         NaN         NaN         NaN  
4           NaN         NaN         NaN         NaN  
..          ...         ...         ...         ...  
190         NaN         NaN         NaN         NaN  
191         NaN         NaN         NaN         NaN  
192         NaN         NaN         NaN         NaN  
193         NaN         NaN         NaN         NaN  
194         NaN         NaN         NaN         NaN  

[195 rows x 25 columns]

In [40]:
df.info() #summary of the dataframe

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 25 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   Customer ID              195 non-null    object 
 1   Entity                   195 non-null    object 
 2   Name                     195 non-null    object 
 3   Surname                  195 non-null    object 
 4   Age at time of purchase  178 non-null    float64
 5   Y                        178 non-null    float64
 6   Gender                   178 non-null    object 
 7   Country                  195 non-null    object 
 8   State                    181 non-null    object 
 9   Purpose                  195 non-null    object 
 10  Deal satisfaction        195 non-null    int64  
 11  Mortgage                 195 non-null    object 
 12  Source                   195 non-null    object 
 13  Unnamed: 13              0 non-null      float64
 14  Unnamed: 14              0

In [42]:
df.shape #number of rows and columns of the dataframe

(195, 25)

In [44]:
df['Unnamed: 15'].unique()

array([nan])

In [46]:
df['Unnamed: 16'].unique()

array([nan, 'SUMMARY OUTPUT', 'Regression Statistics', 'Multiple R',
       'R Square', 'Adjusted R Square', 'Standard Error', 'Observations',
       'ANOVA', 'Regression', 'Residual', 'Total', 'Intercept',
       'X Variable 1'], dtype=object)

In [48]:
df['Unnamed: 17'].unique()

array([nan, '0.996976804', '0.993962748', '0.993928445', '1.000627034',
       '178', 'df', '1', '176', '177', 'Coefficients', '2001.482558',
       '-0.99745197'], dtype=object)

In [50]:
df['Unnamed: 18'].unique()

array([nan, 'SS', '29012.68371', '176.2207851', '29188.90449',
       'Standard Error', '11.48703104', '0.005859631'], dtype=object)

In [52]:
df['Unnamed: 19'].unique()

array([nan, 'MS', '29012.68371', '1.001254461', 't Stat', '174.2384564',
       '-170.2243638'], dtype=object)

In [54]:
df['Unnamed: 20'].unique()

array([nan, 'F', '28976.33403', 'P-value', '5.2803E-199', '3.1169E-197'],
      dtype=object)

In [56]:
df['Unnamed: 21'].unique()

array([nan, 'Significance F', '3.1169E-197', 'Lower 95%', '1978.812508',
       '-1.009016153'], dtype=object)

In [58]:
df['Unnamed: 22'].unique()

array([nan, 'Upper 95%', '2024.152609', '-0.985887786'], dtype=object)

In [60]:
df['Unnamed: 23'].unique()

array([nan, 'Lower 95.0%', '1978.812508', '-1.009016153'], dtype=object)

In [62]:
df['Unnamed: 24'].unique()

array([nan, 'Upper 95.0%', '2024.152609', '-0.985887786'], dtype=object)

In [70]:
# df['Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17'].unique()

In [72]:
unique_values = df[['Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19', 
                    'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24']].apply(lambda x: x.unique())
print(unique_values)

#combining all the columns into one variable and then using the function .apply 

Unnamed: 15                                                [nan]
Unnamed: 16    [nan, SUMMARY OUTPUT, Regression Statistics, M...
Unnamed: 17    [nan, 0.996976804, 0.993962748, 0.993928445, 1...
Unnamed: 18    [nan, SS, 29012.68371, 176.2207851, 29188.9044...
Unnamed: 19    [nan, MS, 29012.68371, 1.001254461, t Stat, 17...
Unnamed: 20    [nan, F, 28976.33403, P-value, 5.2803E-199, 3....
Unnamed: 21    [nan, Significance F, 3.1169E-197, Lower 95%, ...
Unnamed: 22          [nan, Upper 95%, 2024.152609, -0.985887786]
Unnamed: 23        [nan, Lower 95.0%, 1978.812508, -1.009016153]
Unnamed: 24        [nan, Upper 95.0%, 2024.152609, -0.985887786]
dtype: object


In [74]:
df.sample(5) #shows a random sample of the dataset

Customer ID      Entity    Name Surname  Age at time of purchase       Y  \
98        C0141  Individual  Melany  Glover                     47.0  1960.0   
170       C0129  Individual   Jesus  Obrien                     69.0  1938.0   
107       C0039  Individual  Derick      Li                     49.0  1957.0   
39        C0087  Individual  Warren    Pugh                     35.0  1973.0   
140       C0140  Individual   Aniya  Miller                     57.0  1950.0   

    Gender Country       State     Purpose  ...  Unnamed: 15 Unnamed: 16  \
98       F     USA  California  Investment  ...          NaN         NaN   
170      M     USA      Oregon  Investment  ...          NaN         NaN   
107      M     USA  California        Home  ...          NaN         NaN   
39       M     USA     Arizona  Investment  ...          NaN         NaN   
140      F     USA      Nevada        Home  ...          NaN         NaN   

    Unnamed: 17  Unnamed: 18  Unnamed: 19  Unnamed: 20 Unnamed: 21  \
98          NaN          NaN          NaN          NaN         NaN   
170         NaN          NaN          NaN          NaN         NaN   
107         NaN          NaN          NaN          NaN         NaN   
39          NaN          NaN          NaN          NaN         NaN   
140         NaN          NaN          NaN          NaN         NaN   

    Unnamed: 22 Unnamed: 23 Unnamed: 24  
98          NaN         NaN         NaN  
170         NaN         NaN         NaN  
107         NaN         NaN         NaN  
39          NaN         NaN         NaN  
140         NaN         NaN         NaN  

[5 rows x 25 columns]

In [76]:
df.sample(5)

Customer ID      Entity      Name   Surname  Age at time of purchase  \
146       C0079  Individual    Xavier  Faulkner                     60.0   
19        C0093  Individual   Antonio    Porter                     30.0   
1         C0027  Individual      Lara  Carrillo                     22.0   
153       C0013  Individual  Franklin      Mack                     61.0   
51        C0136  Individual   Annabel    Robles                     38.0   

          Y Gender Country       State     Purpose  ...  Unnamed: 15  \
146  1947.0      M  Canada         NaN  Investment  ...          NaN   
19   1977.0      M     USA     Arizona        Home  ...          NaN   
1    1983.0      F     USA  California        Home  ...          NaN   
153  1943.0      M     USA    Virginia        Home  ...          NaN   
51   1969.0      F     USA  California        Home  ...          NaN   

    Unnamed: 16 Unnamed: 17  Unnamed: 18  Unnamed: 19  Unnamed: 20  \
146         NaN         NaN          NaN          NaN          NaN   
19          NaN         NaN          NaN          NaN          NaN   
1           NaN         NaN          NaN          NaN          NaN   
153         NaN         NaN          NaN          NaN          NaN   
51          NaN         NaN          NaN          NaN          NaN   

    Unnamed: 21 Unnamed: 22 Unnamed: 23 Unnamed: 24  
146         NaN         NaN         NaN         NaN  
19          NaN         NaN         NaN         NaN  
1           NaN         NaN         NaN         NaN  
153         NaN         NaN         NaN         NaN  
51          NaN         NaN         NaN         NaN  

[5 rows x 25 columns]